@startuml LoRaWAN DB Schema
entity device {
    *device_id : string <<PK>>
    name : string
    description : string
    created_at : datetime
    updated_at : datetime
}

entity gateway {
    *gateway_id : string <<PK>>
    latitude : number
    longitude : number
    created_at : datetime
    updated_at : datetime
}

entity device_gps_datapoint {
    *id : number <<PK>>
    timestamp : datetime
    device_id : number <<FK>>
    latitude : number
    longitude : number
    altitude : number
    hdop : number
}

entity ttnmapper_datapoint {
    *id : number <<PK; From TTNMapper .csv>>
    timestamp : datetime
    device_gps_datapoint_id : number <<FK>>
    gateway_EUI : string <<FK>>
    rssi : number
    snr : number
}

entity device_subscription {
    *id : number <<PK>>
    device_id : number <<FK>>
    created_at : datetime
    updated_at : datetime
}

gateway "1" -- "1..*" ttnmapper_datapoint
device_gps_datapoint "1" -- "1..*" ttnmapper_datapoint
device "1" -- "1..*" device_gps_datapoint
device "1" -- "1" device_subscription
@enduml