@startuml LoRaWAN DB Schema
entity device {
    *DevEUI : hex <<PK>>
    name : string
    description : string
}

entity gateway {
    *GatewayEUI : hex <<PK>>
    latitude : number
    longitude : number
}

entity device_gps_datapoint {
    *id : number <<PK>>
    device_id : number
    latitude : number
    longitude : number
    altitude : number
    hdop : number
}

entity ttnmapper_datapoint {
    *id : number <<PK; From TTNMapper .csv>>
    device_gps_datapoint_id : number <<FK>>
    GatewayEUI : hex <<FK>>
    rssi : number
    snr : number
}

gateway "1" -- "1..*" ttnmapper_datapoint
device_gps_datapoint "1" -- "1..*" ttnmapper_datapoint
device "1" -- "1..*" device_gps_datapoint
@enduml