name: Build LaTeX document as PDF artifact
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: TeXLive Action (Compile Latex)
        uses: repaction/texlive@mini-v2
        with:
            compiler: pdflatex
            tex_files: thesis/main.tex
            extra_system_packages: "cmap"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: thesis/main.pdf
